### ISSUE TITLE
number of busco databases

### ISSUE THREAD

**Issue by gitcruz** [sanger-tol/blobtoolkit#115]
### Description of feature

Dear developers,

I do have two questions: 

1. I want to pass several databases to BTK's nextflow pipeline (v0.6.0) should I pass them several times using --busco like this:
--busco path-to-databases/busco/vertebrata_odb10
--busco path-to-databases/busco/bacteria_odb10
--busco path-to-databases/busco/fungi_odb10

or with a single line?
--busco path-to-databases/busco/vertebrata_odb10 path-to-databases/busco/bacteria_odb10 path-to-databases/busco/fungi_odb10

2. What is the effect of having a higher number of busco databases in this new version? Apparently the  sensitivity of the taxonomic classification depends on the number of busco databases used (at least since snakemake pipeline v2 was released)

Thanks,
Fernando

**Comment by muffato** [comment]
Hi @gitcruz . The syntax is 
```
--busco path-to-databases/busco/ --busco_lineages vertebrata_odb10,bacteria_odb10,fungi_odb10
```
My understanding is that the sensitivity increases with the number of busco lineages used, because it increases the chance to find a match. @rjchallis may want to comment on that.
Regardless, this part of the pipeline works the same way as in the Snakemake pipeline, so I wouldn't expect any change.

Best,
Matthieu

**Comment by muffato** [comment]
Closing as it seems you've been able to run the pipeline on your own Busco downloads, cf https://github.com/sanger-tol/blobtoolkit/issues/122#issuecomment-2483295090
